-- Insert a user!
INSERT INTO public.users (photo, username, display_name, email, firstname, lastname)
VALUES (null, 'testy', 'TestGuy', 'test@test.com', 'Testy', 'McTesterson'),
       (NULL, 'jdoe', 'John Doe', 'jdoe@test.com', 'John', 'Doe'),
       (NULL, 'asmith', 'Alice Smith', 'asmith@test.com', 'Alice', 'Smith'),
       (NULL, 'bking', 'Bob King', 'bking@test.com', 'Bob', 'King'),
       (NULL, 'cjones', 'Catherine Jones', 'cjones@test.com', 'Catherine', 'Jones'),
       (NULL, 'dgarcia', 'Daniel Garcia', 'dgarcia@test.com', 'Daniel', 'Garcia'),
       (NULL, 'ewilson', 'Emily Wilson', 'ewilson@test.com', 'Emily', 'Wilson'),
       (NULL, 'fwhite', 'Frank White', 'fwhite@test.com', 'Frank', 'White'),
       (NULL, 'ghall', 'Grace Hall', 'ghall@test.com', 'Grace', 'Hall'),
       (NULL, 'hrobinson', 'Hannah Robinson', 'hrobinson@test.com', 'Hannah', 'Robinson')
ON CONFLICT DO NOTHING;

INSERT INTO roles (role_name)
VALUES ('user'),
       ('admin')
ON CONFLICT DO NOTHING;

INSERT INTO user_role (user_id, role_id)
VALUES (1, 1),
       (1, 2),
       (2, 1),
       (3, 1),
       (4, 1),
       (5, 1),
       (6, 1),
       (7, 1),
       (8, 1),
       (9, 1),
       (10, 1);
       

-- Insert Tags
INSERT INTO public.tags (tag_name)
VALUES ('breakfast'),
       ('texmex'),
       ('sauce'),
       ('italian'),
       ('pasta'),
       ('dinner'),
       ('caucasian'),
       ('tofu'),
       ('vegan'),
       ('gluten-free'),
       ('spicy'),
       ('dessert'),
       ('quick'),
       ('healthy'),
       ('comfort food'),
       ('low-carb'),
       ('seafood'),
       ('holiday');


-- Insert Recipes
INSERT INTO public.recipes (author, public, name, description, tags, directions)
VALUES (1, true, 'Spicy Braised Tofu',
        'Tofu braised with soy sauce, mirin, and gochugaru, served with scallions and sesame seeds.', '{6,8}',
        '1. Wrap tofu in a clean kitchen towel and place on a rimmed baking sheet. Weigh down with a heavy object (a couple of heavy cans works well) and let sit 10 minutes. Unwrap tofu and slice in half lengthwise, then cut crosswise into 6 sections to create 12 squares. 2. Whisk soy sauce, mirin, sesame oil, gochugaru, and 3 Tbsp. water in a small bowl to combine; set sauce aside. 3. Trim dark green top from scallion and thinly slice; set aside. Thinly slice remaining white and pale green parts of scallion. Heat 1 Tbsp. grapeseed oil in a nonstick skillet over medium-high. Carefully add tofu in a single layer and lightly season with salt. Cook, undisturbed, until golden brown, about 5 minutes; turn over and cook until golden brown on other side, about 5 minutes. Transfer tofu to a plate; reserve skillet (no need to wipe out). 4. Heat remaining 1 Tbsp. grapeseed oil in reserved skillet over medium. Cook scallion white and pale green parts, garlic, and ginger, stirring, until softened but not browned, about 1 minute. 5. Return tofu to skillet. Pour in reserved sauce and bring to a simmer. Reduce heat to medium-low and cook, turning tofu once or twice and occasionally spooning sauce over, until sauce is reduced by about half, about 4 minutes. 6. Transfer tofu to a large plate, spoon sauce over, and sprinkle with sesame seeds and reserved scallion top. Serve with rice alongside.');
INSERT INTO public.recipes (author, public, name, description, tags, directions)
VALUES (1, true, 'Pasta Bake',
        'A comforting pasta bake with elbow pasta, spinach, kidney beans, Beyond beef, cheddar cheese, and a blend of spices, topped with a squeeze of lime and sour cream.',
        '{5,6,7}',
        '1. Bring lightly salted water to a boil, then add pasta. 2. While waiting for that, cook spinach and Beyond beef according to directions. 3. Cook pasta to desired doneness. 4. Combine pasta, beans, and spinach in a glass baking dish. 5. Add seasonings and lime juice. 6. Add cheese on top and mix partway into top layer. 7. Bake at 350°F for 10 minutes. 8. Serve topped with sour cream.');
INSERT INTO public.recipes (author, public, name, description, tags, directions)
VALUES (1, true, 'Marinara Sauce',
        'A classic marinara sauce made with olive oil, onions, garlic, basil, and whole peeled tomatoes. Perfect for pasta dishes or as a base for other recipes.',
        '{3,4}',
        '1. Heat oil in a medium heavy pot over medium. 2. Cook onion, stirring occasionally, until very soft, 8–10 minutes. 3. Add garlic and cook, stirring occasionally, until very soft, about 5 minutes; stir in basil. 4. Add tomatoes, crushing with your hands as you go; season with salt and pepper and bring to a simmer. 5. Reduce heat; simmer gently, stirring occasionally, until sauce is thick, about 1 hour. 6. Season with salt and pepper. 7. Let cool.');
INSERT INTO public.recipes (author, public, name, description, tags, directions)
VALUES (1, true, 'Migas',
        'A flavorful Tex-Mex breakfast dish with crispy corn tortillas, eggs, cheese, and a mix of vegetables and spices. Optionally garnished with red onion, cotija, cilantro, and salsa.',
        '{1,2}',
        '1. Heat butter and 1 tablespoon oil in a large skillet over medium-high. Tear the tortillas into 1-inch pieces and add them to the pan, fanning them out so they all touch the oil and butter. Fry, using a spatula to flip and shift the tortillas around, until crispy and browned, about 5 minutes. 2. Move the tortillas to one side of the pan, add the remaining tablespoon oil and then the onion and jalapeño. Cook, stirring often, until the onion is translucent and the jalapeño is softened, about 4 minutes. Add the garlic and cook, stirring often, until softened, 2 minutes. Season with cumin, ½ Tsp salt and 1 Tsp pepper, and stir to combine with the tortillas, then turn the heat down to low. 3. In a bowl, whisk together the eggs and milk. Follow with the shredded cheese, whisking to combine. Turn the heat up to medium-low and slowly pour the egg mixture into the pan, using a spatula to move the eggs around as they begin to cook. Continue to softly scramble the eggs, incorporating them with the other ingredients and pulling the pan off of the heat when they’re solid but still a little runny, about 7 minutes. The residual heat will continue to cook the eggs without toughening or drying them out. 4. Serve immediately, garnished with red onion, cotija, cilantro and salsa if desired.');
INSERT INTO recipes (author, public, name, description, tags, directions)
VALUES (3, -- Random user_id between 1 and 10
        true,
        'Pasta Aglio e Olio',
        'Pasta Aglio e Olio inspired by Chef',
        ARRAY [(SELECT tag_id FROM tags WHERE tag_name = 'pasta'), (SELECT tag_id FROM tags WHERE tag_name = 'dinner')],
        '1. Heavily salt a large pot of water, and bring to a boil.\n2. Cook pasta until slightly underdone.\n3. Slice the garlic cloves thinly, and set aside.\n4. Heat olive oil in a large sauté pan over medium heat until barely shimmering.\n5. Add sliced garlic, stirring constantly, until softened and turning golden on the edges.\n6. Add the red pepper flakes and lower the heat to medium-low.\n7. Add the pasta, drained, with about 1/4 cup reserved pasta cooking water.\n8. Squeeze lemon juice over top, and mix into the pasta with the fresh parsley.\n9. If sauce is too watery, continue to cook for 1-3 minutes, until pasta has absorbed more liquid.\n10. Season with salt and pepper, and serve.');
INSERT INTO recipes (author, public, name, description, tags, directions)
VALUES (4, -- Replace with a random user ID between 1 and 10
        TRUE,
        'Gochujang-Sesame Noodles',
        'Fresh or dried wheat noodles tossed with a spicy gochujang sauce and topped with basil and sesame seeds.',
        ARRAY [(SELECT tag_id FROM tags WHERE tag_name = 'dinner'),
                (SELECT tag_id FROM tags WHERE tag_name = 'spicy')],
        '1. Cook noodles in a large pot of boiling salted water according to package directions. Drain and rinse under cool running water.\n ' ||
        '2. Whisk gochujang, soy sauce, brown sugar, tahini, sesame oil, and 2 Tbsp. water in a small bowl to combine; set sauce aside.\n ' ||
        '3. Heat vegetable oil in a wok or large nonstick skillet over medium-high. Add broccoli rabe and garlic; season with salt and lots of pepper. ' ||
        '4. Cook, tossing often, until broccoli rabe stems are crisp-tender and leaves are wilted, about 2 minutes. \n' ||
        '5. Add reserved sauce and cook, stirring often, until thickened slightly, about 2 minutes. \n' ||
        '6. Add noodles and a handful of basil and toss gently until sauce clings to noodles, about 1 minute. \n' ||
        '7. Divide noodles among bowls and top with sesame seeds and more basil. Serve with lime wedges for squeezing over.');
INSERT INTO recipes (author, public, name, description, tags, directions)
VALUES (7, -- Replace with a random user ID between 1 and 10
        TRUE,
        'Rice Noodles with Cashew Sauce and Crunchy Veg',
        'Rice noodles tossed with a creamy cashew sauce and crunchy fresh vegetables.',
        ARRAY [(SELECT tag_id FROM tags WHERE tag_name = 'dinner'),
                (SELECT tag_id FROM tags WHERE tag_name = 'cold')],
        '1. Preheat oven to 350º. Toast cashews on a rimmed baking sheet, tossing halfway through, until golden brown, 10–12 minutes; let cool. Coarsely crush ⅓ cup cashews with a flat-bottomed mug; set aside. Transfer remaining 1 cup cashews to a blender. Add ginger, chile, garlic, tamari, oil, 3 Tbsp. lime juice, and ¼ cup hot water. Purée on high speed, adding more hot water by the tablespoonful if needed, until dressing is smooth and creamy. ' ||
        '2. Cook noodles according to package directions. Rinse under water, then drain. Transfer to a medium bowl. Add a pinch of salt and 1 Tbsp. lime juice and toss to combine. ' ||
        '3. Toss cucumber, radishes, carrots, scallions, parsley, remaining 2 Tbsp. lime juice, and a big pinch of salt in a large bowl. ' ||
        '4. Spread ¼ cup cashew dressing in each bowl. Divide noodles and crunchy vegetables among bowls. Top with reserved crushed cashews. Serve with leftover sauce alongside, if desired.');
INSERT INTO recipes (author, public, name, description, tags, directions)
VALUES (7, TRUE, 'One Pot Homemade Hamburger Helper', NULL, ARRAY [
        (SELECT tag_id FROM public.tags WHERE tag_name ILIKE 'dinner' LIMIT 1),
    (SELECT tag_id FROM public.tags WHERE tag_name ILIKE 'caucasian' LIMIT 1)
    ],
        '1. Cook the ground beef in a large skillet over medium high heat until no longer pink. Drain grease and return meat to the pan. 
        2. Reduce heat to low and add the ketchup, mustard, hot sauce, seasonings, macaroni and broth to the pan and stir well to combine. 
        3. Cover and simmer for 12-15 minutes until macaroni is cooked through. 
        4. Remove pan from heat and stir in the sour cream. 
        5. Return the pan to the warm burner and stir in the shredded cheese until well combined.');
INSERT INTO recipes (author, public, name, description, tags, directions)
VALUES (5, TRUE, 'Curry Paneer Fried Rice', NULL, ARRAY [
        (SELECT tag_id FROM public.tags WHERE tag_name ILIKE 'dinner' LIMIT 1),
        (SELECT tag_id FROM public.tags WHERE tag_name ILIKE 'rice' LIMIT 1),
        (SELECT tag_id FROM public.tags WHERE tag_name ILIKE 'indian' LIMIT 1)
    ],
        '1. In a nonstick pan on medium-high, heat oil then add red onion and cook, stirring occasionally, until translucent, 2 to 3 minutes. 
        2. Add the curry powder, 1 Tsp salt and the paneer. 
        3. Cook, stirring occasionally, until paneer is cooked through, 5 to 6 minutes. 
        4. Add the frozen vegetables and 1 Tsp pepper and cook, stirring, 1 minute. 
        5. Stir in the rice, making sure to flatten any clumps of rice to ensure the rice gets evenly covered with the oil and spices. 
        6. Cook until the rice is heated through, about 4 minutes. 
        7. Adjust for seasoning, then stir in the cilantro. 
        8. Serve hot, topped with scallions and fried eggs (if using).');
INSERT INTO recipes (author, public, name, description, tags, directions)
VALUES (7, TRUE, 'Egg Drop Soup', NULL, ARRAY [
        (SELECT tag_id FROM public.tags WHERE tag_name ILIKE 'soup' LIMIT 1),
        (SELECT tag_id FROM public.tags WHERE tag_name ILIKE 'dinner' LIMIT 1),
        (SELECT tag_id FROM public.tags WHERE tag_name ILIKE 'snack' LIMIT 1)
    ],
        '1. Bring the stock to a simmer in a medium soup pot. Stir in the sesame oil, salt, sugar, white pepper, and turmeric. 
        2. Next add the cornstarch and water mixture. Make sure the cornstarch and water is mixed well, as the cornstarch settles very quickly. Stir the soup continuously as you drizzle in the slurry, or you''ll get clumps of cooked starch in your soup. Use more or less starch if you like a thicker or thinner soup. You can also add the starch in a couple small batches, let the soup simmer for a couple of minutes, then check to see if the consistency is to your liking. 
        3. Now we''re ready for the most exciting part: the egg. This recipe calls for the egg to be lightly beaten, which results in both white and yellow egg swirls. The speed at which you stir the soup when adding the egg also determines whether you get large “egg flowers” or small egg flowers (i.e. swirly bits of egg). Use a ladle to stir the soup in a circular motion, and slowly drizzle in the egg until you have added it all. 
        4. Ladle the soup into bowls, top with scallions, and serve.');


-- Insert Measurements
INSERT INTO public.measurements (name, unit_measure, type)
VALUES ('block', 1, 'unit'),
       ('Tbsp', 14.8, 'volume'),
       ('tsp', 4.9, 'volume'),
       ('bag', 1, 'unit'),
       ('can', 1, 'unit'),
       ('cup', 236.6, 'volume'),
       ('sprigs', 1, 'unit'),
       ('unit', 1, 'unit'),
       ('lb', 453.6, 'weight'),
       ('ounces', 28.35, 'weight'),
       ('gram', 1, 'weight'),
       ('ml', 1, 'volume');
       


-- Insert Ingredients
INSERT INTO public.ingredients (name, description, tags)
VALUES ('Tofu', null, null),
       ('Soy sauce', null, null),
       ('Mirin', null, null),
       ('Toasted sesame oil', null, null),
       ('Gochugaru', 'Korean red pepper flakes', null),
       ('Scallion', null, null),
       ('Grapeseed oil', null, null),
       ('Kosher salt', null, null),
       ('Garlic', null, null),
       ('Ginger', null, null),
       ('Toasted sesame seeds', null, null),
       ('Cooked rice', null, null),
       ('Elbow pasta', null, null),
       ('Frozen chopped spinach', null, null),
       ('Shredded sharp cheddar cheese', null, null),
       ('Kidney beans', null, null),
       ('Lime', null, null),
       ('Chili powder', null, null),
       ('Ground cumin', null, null),
       ('Paprika', null, null),
       ('Crushed red pepper', null, null),
       ('Salt', null, null),
       ('Garlic powder', null, null),
       ('Onion powder', null, null),
       ('Dried oregano', null, null),
       ('Onion', null, null),
       ('Garlic cloves', null, null),
       ('Whole peeled tomatoes', null, null),
       ('Black pepper', null, null),
       ('Beyond beef', null, null),
       ('Olive oil', null, null),
       ('Basil', null, null),
       ('Sesame oil', null, null),
       ('diced red onion', null, null),
       ('cilantro', null, null),
       ('salsa', null, null),
       ('cotija cheese', null, null),
       ('Sesame seeds', null, null),
       ('Rice', null, null),
       ('spinach', null, null),
       ('Cheddar cheese', null, null),
       ('Butter', null, null),
       ('vegetable oil', null, null),
       ('Corn tortillas', null, null),
       ('Yellow onion', null, null),
       ('Jalapeno', null, null),
       ('Eggs', null, null),
       ('Shredded cheese', null, null),
       ('Whole milk', null, null),
       ('flat leaf parsley', NULL, NULL),
       ('dry linguine', NULL, NULL),
       ('lemon', NULL, NULL),
       ('Wheat noodles', NULL, NULL),
       ('Gochujang', NULL, NULL),
       ('Light brown sugar', NULL, NULL),
       ('Tahini', NULL, NULL),
       ('Vegetable oil', NULL, NULL),
       ('Broccoli rabe', NULL, NULL),
       ('Fresh basil leaves', NULL, NULL),
       ('Lime wedges', NULL, NULL),
       ('Cashews', NULL, NULL),
       ('Ginger', NULL, NULL),
       ('Red chile', NULL, NULL),
       ('Tamari', NULL, NULL),
       ('Persian cucumber', NULL, NULL),
       ('Radishes', NULL, NULL),
       ('Carrots', NULL, NULL),
       ('Scallions', NULL, NULL),
       ('Parsley', NULL, NULL),
       ('Ground Beef', NULL, NULL),
       ('Ketchup', NULL, NULL),
       ('Dijon Mustard', NULL, NULL),
       ('Hot Sauce', NULL, NULL),
       ('Garlic Powder', NULL, NULL),
       ('Onion Powder', NULL, NULL),
       ('Seasoning Salt', NULL, NULL),
       ('Macaroni', NULL, NULL),
       ('Broth', NULL, NULL),
       ('Sour Cream', NULL, NULL),
       ('Shredded Cheddar Cheese', NULL, NULL),
       ('Canola oil', NULL, NULL),
       ('Red onion', NULL, NULL),
       ('Paneer', NULL, NULL),
       ('Frozen mixed vegetables', 'Such as carrots, green beans, corn, and peas', NULL),
       ('Cooked rice', NULL, NULL),
       ('Fresh parsley', NULL, NULL),
       ('Scallions', NULL, NULL),
       ('Fried eggs', NULL, NULL),
       ('Vegetable broth', NULL, NULL),
       ('Cornstarch', NULL, NULL),
       ('Turmeric', NULL, NULL),
       ('Red pepper flakes', NULL, NULL),
       ('Lime juice', NULL, NULL),
       ('Rice noodles', NULL, NULL),
       ('Curry powder', NULL, NULL),
       ('White pepper', NULL, NULL),
       ('Sugar', NULL, NULL)
ON CONFLICT DO NOTHING;


-- Add ingredients to recipes!
INSERT INTO ingr_recipe (recipe_id, ingr_id, quantity, measurement, note, section)
VALUES (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'tofu' LIMIT 1), 1, 1,
        'firm or extra-firm, drained', NULL),
       (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'soy sauce' LIMIT 1), 3, 2,
        NULL, NULL),
       (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'mirin' LIMIT 1), 3, 2,
        NULL, NULL),
       (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'sesame oil' LIMIT 1), 1, 3,
        NULL, NULL),
       (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'gochugaru' LIMIT 1), 0.75,
        3, NULL, NULL),
       (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'scallion' LIMIT 1), 1,
        NULL, NULL, NULL),
       (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'grapeseed oil' LIMIT 1), 2,
        2, 'divided', NULL),
       (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'salt' LIMIT 1), NULL, NULL,
        'to taste', NULL),
       (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'garlic' LIMIT 1), 1, NULL,
        'small, finely chopped', NULL),
       (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'ginger' LIMIT 1), 1, 3,
        'finely chopped, peeled', NULL),
       (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'sesame seeds' LIMIT 1),
        NULL, NULL, 'for serving', NULL),
       (1, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'rice' LIMIT 1), NULL, NULL,
        'for serving', NULL),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'elbow pasta' LIMIT 1), 0.5,
        4, NULL, NULL),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'spinach' LIMIT 1), 1, 1,
        NULL, NULL),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'cheddar cheese' LIMIT 1),
        NULL, NULL, 'shredded', NULL),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'kidney beans' LIMIT 1), 1,
        5, NULL, NULL),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'beyond beef' LIMIT 1),
        NULL, NULL, NULL, NULL),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'lime' LIMIT 1), NULL, NULL,
        'juice', NULL),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'chili powder' LIMIT 1), 2,
        3, NULL, 'Seasoning'),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'ground cumin' LIMIT 1), 3,
        3, NULL, 'Seasoning'),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'paprika' LIMIT 1), 1, 3,
        NULL, 'Seasoning'),
       (2,
        (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'crushed red pepper' LIMIT 1),
        1, 3, NULL, 'Seasoning'),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'salt' LIMIT 1), 1, 3, NULL,
        'Seasoning'),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'garlic powder' LIMIT 1),
        0.5, 3, NULL, 'Seasoning'),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'onion powder' LIMIT 1),
        0.5, 3, NULL, 'Seasoning'),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'dried oregano' LIMIT 1),
        0.5, 3, NULL, 'Seasoning'),
       (2, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'black pepper' LIMIT 1),
        0.5, 3, NULL, 'Seasoning'),
       (3, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'olive oil' LIMIT 1), 0.25,
        6, NULL, NULL),
       (3, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'onion' LIMIT 1), 1, NULL,
        'small, finely chopped', NULL),
       (3, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'garlic' LIMIT 1), 4, NULL,
        'thinly sliced', NULL),
       (3, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'basil' LIMIT 1), 2, 7,
        NULL, NULL),
       (3, (SELECT ingredients.ingr_id
            FROM public.ingredients
            WHERE ingredients.name ILIKE 'whole peeled tomatoes'
            LIMIT 1), 2, 5, NULL, NULL),
       (3, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'kosher salt' LIMIT 1),
        NULL, NULL, 'to taste', NULL),
       (3, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'black pepper' LIMIT 1),
        NULL, NULL, 'to taste', NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'butter' LIMIT 1), 1, 2,
        NULL, NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'vegetable oil' LIMIT 1), 2,
        2, NULL, NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'corn tortillas' LIMIT 1),
        6, 8, NULL, NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'yellow onion' LIMIT 1), 1,
        NULL, 'small, diced', NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'jalapeno' LIMIT 1), 1,
        NULL, 'seeded if desired, and diced', NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'garlic' LIMIT 1), 2, NULL,
        'minced', NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'ground cumin' LIMIT 1),
        0.5, 2, NULL, NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'salt' LIMIT 1), NULL, NULL,
        'to taste', NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'black pepper' LIMIT 1),
        NULL, NULL, 'to taste', NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'Eggs' LIMIT 1), 6, NULL,
        'Large', NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'whole milk' LIMIT 1), 0.25,
        6, NULL, NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'shredded cheese' LIMIT 1),
        1, 6, 'Mexican blend or Cheddar', NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'diced red onion' LIMIT 1),
        NULL, NULL, 'for serving (optional)', NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'cotija cheese' LIMIT 1),
        NULL, NULL, 'for serving (optional)', NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'cilantro' LIMIT 1), NULL,
        NULL, 'for serving (optional)', NULL),
       (4, (SELECT ingredients.ingr_id FROM public.ingredients WHERE ingredients.name ILIKE 'salsa' LIMIT 1), NULL,
        NULL, 'for serving (optional)', NULL),
       (5,
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'garlic' LIMIT 1),
        0.5,
        NULL,
        'head',
        NULL),
       (5,
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'flat leaf parsley' LIMIT 1),
        0.5,
        (SELECT meas_id FROM measurements WHERE name = 'cup'),
        NULL,
        NULL),
       (5,
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'olive oil' LIMIT 1),
        0.5,
        (SELECT meas_id FROM measurements WHERE name = 'cup'),
        NULL,
        NULL),
       (5,
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'red pepper flakes' LIMIT 1),
        1,
        (SELECT meas_id FROM measurements WHERE name = 'tsp'),
        NULL,
        NULL),
       (5,
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'dry linguine' LIMIT 1),
        0.5,
        (SELECT meas_id FROM measurements WHERE name = 'lb'),
        NULL,
        NULL),
       (5,
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'lemon' LIMIT 1),
        0.5,
        NULL,
        NULL,
        NULL),
       (5,
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'salt' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL),
       (5,
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'black pepper' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL),
       (5, -- Pasta Aglio e Olio recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Wheat noodles' LIMIT 1),
        NULL,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (5, -- Pasta Aglio e Olio recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Gochujang' LIMIT 1),
        0.25,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'cup' LIMIT 1),
        NULL,
        NULL),
       (5, -- Pasta Aglio e Olio recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Light brown sugar' LIMIT 1),
        2,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'Tbsp' LIMIT 1),
        NULL,
        NULL),
       (5, -- Pasta Aglio e Olio recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Tahini' LIMIT 1),
        2,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'Tbsp' LIMIT 1),
        NULL,
        NULL),
       (5, -- Pasta Aglio e Olio recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Toasted sesame oil' LIMIT 1),
        2,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'tsp' LIMIT 1),
        NULL,
        NULL),
       (5, -- Pasta Aglio e Olio recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Vegetable oil' LIMIT 1),
        2,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'Tbsp' LIMIT 1),
        NULL,
        NULL),
       (5, -- Pasta Aglio e Olio recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Broccoli rabe' LIMIT 1),
        1,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (5, -- Pasta Aglio e Olio recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Garlic' LIMIT 1),
        4,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (5, -- Pasta Aglio e Olio recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Fresh basil leaves' LIMIT 1),
        1,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (5, -- Pasta Aglio e Olio recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Toasted sesame seeds' LIMIT 1),
        NULL,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (5, -- Pasta Aglio e Olio recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Lime wedges' LIMIT 1),
        NULL,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Cashews' LIMIT 1),
        1.33,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'cup' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Ginger' LIMIT 1),
        1,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        '1-inch piece',
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Red chile' LIMIT 1),
        0.5,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Garlic' LIMIT 1),
        2,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Tamari' LIMIT 1),
        3,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'Tbsp' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Toasted sesame oil' LIMIT 1),
        1,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'tsp' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Lime juice' LIMIT 1),
        6,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'Tbsp' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Rice noodles' LIMIT 1),
        4,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'ounces' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Persian cucumber' LIMIT 1),
        1,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Radishes' LIMIT 1),
        4,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Carrots' LIMIT 1),
        2,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Scallions' LIMIT 1),
        2,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'unit' LIMIT 1),
        NULL,
        NULL),
       (7, -- Rice Noodles with Cashew Sauce and Crunchy Veg recipe ID
        (SELECT ingr_id FROM ingredients WHERE name ILIKE 'Parsley' LIMIT 1),
        1,
        (SELECT meas_id FROM measurements WHERE name ILIKE 'cup' LIMIT 1),
        NULL,
        NULL),
       (8, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Ground Beef' LIMIT 1), 1,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'unit' LIMIT 1), NULL, 'Main'),
       (8, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Ketchup' LIMIT 1), 1,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'unit' LIMIT 1), NULL, 'Condiments'),
       (8, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Dijon Mustard' LIMIT 1), 1,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'unit' LIMIT 1), NULL, 'Condiments'),
       (8, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Macaroni' LIMIT 1), 1.5,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'cup' LIMIT 1), NULL, 'Pasta'),
       (8, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Broth' LIMIT 1), 3.5,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'cup' LIMIT 1), NULL, 'Liquid'),
       (8, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Sour Cream' LIMIT 1), 0.5,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'cup' LIMIT 1), NULL, 'Dairy'),
       (8, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Shredded Cheddar Cheese' LIMIT 1), 2,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'cup' LIMIT 1), NULL, 'Dairy'),
       (9, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Canola oil' LIMIT 1), 0.25,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'cup' LIMIT 1), NULL, 'Oil'),
       (9, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Red onion' LIMIT 1), 0.5,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'cup' LIMIT 1), NULL, 'Vegetables'),
       (9, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Curry powder' LIMIT 1), 1.5,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'Tbsp' LIMIT 1), NULL, 'Spices'),
       (9, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Paneer' LIMIT 1), 0.5,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'lb' LIMIT 1), NULL, 'Protein'),
       (9, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Frozen mixed vegetables' LIMIT 1), 1.5,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'cup' LIMIT 1), NULL, 'Vegetables'),
       (9, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Cooked rice' LIMIT 1), 2.5,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'cup' LIMIT 1), NULL, 'Grains'),
       (9, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Fresh parsley' LIMIT 1), 0.33,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'cup' LIMIT 1), NULL, 'Herbs'),
       (9, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Scallions' LIMIT 1), NULL,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'unit' LIMIT 1), 'For serving', 'Garnish'),
       (9, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Fried eggs' LIMIT 1), NULL,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'unit' LIMIT 1), 'Optional, for serving', 'Garnish'),
       (10, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Vegetable broth' LIMIT 1), 4,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'cup' LIMIT 1), NULL, 'Broth'),
       (10, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Sesame oil' LIMIT 1), 0.5,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'Tsp' LIMIT 1), NULL, 'Oil'),
       (10, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Salt' LIMIT 1), 0.75,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'Tsp' LIMIT 1), NULL, 'Seasoning'),
       (10, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Sugar' LIMIT 1), 0.125,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'Tsp' LIMIT 1), NULL, 'Seasoning'),
       (10, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'White pepper' LIMIT 1), 0.125,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'Tsp' LIMIT 1), NULL, 'Seasoning'),
       (10, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Turmeric' LIMIT 1), 0.5,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'Tsp' LIMIT 1), NULL, 'Spices'),
       (10, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Cornstarch' LIMIT 1), 3,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'Tbsp' LIMIT 1), NULL, 'Thickener'),
       (10, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Eggs' LIMIT 1), 3,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'unit' LIMIT 1), 'Lightly beaten', 'Protein'),
       (10, (SELECT ingr_id FROM public.ingredients WHERE name ILIKE 'Scallion' LIMIT 1), 1,
        (SELECT meas_id FROM public.measurements WHERE name ILIKE 'unit' LIMIT 1), 'Chopped, for topping', 'Garnish')
ON CONFLICT DO NOTHING;

INSERT INTO access (user_id, recipe_id, view, comment, edit) VALUES
(1, 1, TRUE, FALSE, TRUE),
(2, 2, FALSE, TRUE, FALSE),
(3, 3, TRUE, TRUE, TRUE),
(4, 4, FALSE, FALSE, TRUE),
(5, 5, TRUE, FALSE, FALSE),
(6, 6, TRUE, TRUE, FALSE),
(7, 7, FALSE, TRUE, TRUE),
(8, 8, TRUE, FALSE, TRUE),
(9, 9, FALSE, FALSE, FALSE),
(10, 10, TRUE, TRUE, TRUE);

INSERT INTO comments (user_id, recipe_id, comment) VALUES
(1, 1, 'This recipe was amazing! Loved every bite.'),
(2, 2, 'Not bad, but it could use a bit more seasoning.'),
(3, 3, 'I would definitely make this again. Simple and tasty!'),
(4, 4, 'The flavors were a bit too strong for my taste.'),
(5, 5, 'My family enjoyed this recipe. Thanks for sharing!'),
(6, 6, 'This was okay, but I prefer a different style of cooking.'),
(7, 7, 'Excellent dish! I will recommend it to my friends.'),
(8, 8, 'Could use more spice. A little bland for my preference.'),
(9, 9, 'Great recipe, easy to follow and delicious.'),
(10, 10, 'I had high hopes, but it didn’t turn out as expected.');

INSERT INTO notes (user_id, recipe_id, note) VALUES
(1, 1, 'Reduce the amount of garlic next time. It was a bit overpowering.'),
(2, 2, 'Try using white wine vinegar instead of regular vinegar for a lighter taste.'),
(3, 3, 'Add a pinch of sugar to balance the acidity of the tomatoes.'),
(4, 4, 'Use low-sodium broth to make it less salty.'),
(5, 5, 'Substitute chicken for beef to make it a bit lighter.'),
(6, 6, 'Add a splash of cream to make the sauce richer.'),
(7, 7, 'Try adding a squeeze of lemon juice for a fresh finish.'),
(8, 8, 'Use half the recommended amount of salt to reduce sodium.'),
(9, 9, 'Add some fresh herbs at the end for a burst of flavor.'),
(10, 10, 'Reduce the cooking time slightly for a more tender result.');

INSERT INTO ratings (user_id, recipe_id, rating) VALUES
(1, 3, 4),
(2, 5, 2),
(3, 8, 5),
(4, 1, 3),
(5, 7, 1),
(6, 4, 4),
(7, 2, 5),
(8, 6, 3),
(9, 10, 2),
(10, 9, 4);

