CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TYPE measure_type AS ENUM ('volume', 'weight', 'unit');
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE ingredients (
    ingr_id bigint GENERATED ALWAYS AS IDENTITY,
    name citext,
    description text,
    tags bigint[],
    CONSTRAINT ingredients_pkey PRIMARY KEY (ingr_id)
);

CREATE TABLE measurements (
    meas_id bigint GENERATED ALWAYS AS IDENTITY,
    name text,
    unit_measure numeric NOT NULL,
    type measure_type NOT NULL,
    CONSTRAINT measurements_pkey PRIMARY KEY (meas_id)
);

CREATE TABLE "Messages" (
    "MsgId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MsgText" text,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("MsgId")
);

CREATE TABLE roles (
    role_id bigint GENERATED ALWAYS AS IDENTITY,
    role_name text NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE tags (
    tag_id bigint GENERATED ALWAYS AS IDENTITY,
    tag_name text,
    CONSTRAINT tags_pkey PRIMARY KEY (tag_id)
);

CREATE TABLE users (
    user_id bigint GENERATED ALWAYS AS IDENTITY,
    photo bytea,
    username text,
    display_name text,
    email text,
    firstname text,
    lastname text,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE recipes (
    recipe_id bigint GENERATED ALWAYS AS IDENTITY,
    author bigint,
    public boolean,
    name text,
    description text,
    tags bigint[],
    directions text,
    CONSTRAINT recipes_pkey PRIMARY KEY (recipe_id),
    CONSTRAINT recipes_author_fkey FOREIGN KEY (author) REFERENCES users (user_id)
);

CREATE TABLE user_role (
    role_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_role_pkey PRIMARY KEY (role_id, user_id),
    CONSTRAINT role_user_fkey FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE CASCADE,
    CONSTRAINT user_role_fkey FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE access (
    user_id bigint NOT NULL,
    recipe_id bigint NOT NULL,
    view boolean DEFAULT TRUE,
    comment boolean DEFAULT TRUE,
    edit boolean DEFAULT FALSE,
    CONSTRAINT access_pkey PRIMARY KEY (user_id, recipe_id),
    CONSTRAINT access_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT access_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE comments (
    user_id bigint,
    recipe_id bigint,
    comment text,
    CONSTRAINT comments_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE ingr_recipe (
    recipe_id bigint NOT NULL,
    ingr_id bigint NOT NULL,
    quantity numeric,
    measurement bigint,
    note text,
    section text,
    CONSTRAINT ingr_recipe_pkey PRIMARY KEY (recipe_id, ingr_id),
    CONSTRAINT ingr_recipe_ingr_id_fkey FOREIGN KEY (ingr_id) REFERENCES ingredients (ingr_id) ON DELETE RESTRICT,
    CONSTRAINT ingr_recipe_measurement_fkey FOREIGN KEY (measurement) REFERENCES measurements (meas_id) ON DELETE RESTRICT,
    CONSTRAINT ingr_recipe_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE
);

CREATE TABLE notes (
    user_id bigint,
    recipe_id bigint,
    note text,
    CONSTRAINT notes_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE ratings (
    user_id bigint NOT NULL,
    recipe_id bigint NOT NULL,
    rating integer,
    CONSTRAINT ratings_pkey PRIMARY KEY (user_id, recipe_id),
    CONSTRAINT ratings_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT ratings_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX "IX_access_recipe_id" ON access (recipe_id);

CREATE INDEX "IX_comments_recipe_id" ON comments (recipe_id);

CREATE INDEX "IX_comments_user_id" ON comments (user_id);

CREATE INDEX "IX_ingr_recipe_ingr_id" ON ingr_recipe (ingr_id);

CREATE INDEX "IX_ingr_recipe_measurement" ON ingr_recipe (measurement);

CREATE UNIQUE INDEX ingredients_name_key ON ingredients (name);

CREATE INDEX "IX_notes_recipe_id" ON notes (recipe_id);

CREATE INDEX "IX_notes_user_id" ON notes (user_id);

CREATE INDEX "IX_ratings_recipe_id" ON ratings (recipe_id);

CREATE INDEX "IX_recipes_author" ON recipes (author);

CREATE INDEX "IX_user_role_user_id" ON user_role (user_id);

CREATE UNIQUE INDEX users_display_name_key ON users (display_name);

CREATE UNIQUE INDEX users_email_key ON users (email);

CREATE UNIQUE INDEX users_username_key ON users (username);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240813192744_InitialCreate', '8.0.7');

COMMIT;


